all: arranjos2.pdf enderecamento.pdf fluxo.pdf lineares.pdf taxonomia.pdf arranjos3.pdf expressoes.pdf graficas.pdf logicas-esquema.pdf arranjos.pdf fluxo-exercicio.pdf introducao.pdf logicas.pdf
include ../../Makefile.base
