* Compiladores (INF01147)

Seja bemvinda(o) a disciplina de compiladores, passagem obrigatória
para os alunos de CIC (Ciência da Computação) e ECP (Engenharia da
Computação) do INF (Instituto de Informática) da UFRGS (Universidade
Federal do Rio Grande do Sul). Grande parte do material da disciplina
está em português brasileiro [pt-br]. Disponibilizamos aqui os slides
utilizados pelo professor, material de apoio, exercícios, assim como a
especificação do projeto de compilador.

** Estratégia Pedagógica

As aulas são majoritariamente expositivas; com exercícios em aula com
acompanhamento do professor e resolução ao final do encontro. Aulas
práticas pontuais são utilizadas para averiguar o bom andamento do
projeto de compilador. Experimentalmente, são empregados métodos
alternativos de ensino com o objetivo de melhorar o aprendizado
da disciplina. Os dois documentos abaixo fornecem um apanhado dessas
estratégias pedagógicas alternativas:

- [[download/compiladores-projeto-inovacao.pdf][Compilando Interações (Projeto de inovação didática - PAAP/UFRGS 2014)]]
- [[http://www.lume.ufrgs.br/handle/10183/147664][Aprendizado invertido em compiladores (TCC de Lucas Jones - 2016)]]

** Plano e Cronograma

- [[plano/index.org][Plano da disciplina]] (permanente), com detalhamento dos seguintes itens
  - Conteúdo programático
  - Metodologia
  - Experiências de aprendizagem
  - Critérios de avaliação
  - Atividades de recuperação
  - Bibliografia
- [[cronograma/index.org][Cronograma]]
  - Edição 2017/2 - Turma A
  - Segundas e Quartas, 10:30 – 12:10

** Conteúdo

- [[conteudo/index.org][Conteúdo da disciplina]]
  - Aulas e videoaulas
  - Material de apoio
  - Exercícios

** Projeto de Compilador

- [[projeto/index.org][Projeto de Compilador]]
  - Apresentação
  - Especificação das etapas
  - Forma de avaliação

** Contato

Se você encontrar algum problema, e também no caso de dúvidas, entre em contato por e-mail:
- [[schnorr@inf.ufrgs.br][Prof. Lucas (schnorr@inf.ufrgs.br)]]
