# -*- coding: utf-8 -*-
# -*- mode: org -*-

#+Title: Geração de Código, Endereçamento de Arranjos
#+Author: Prof. Lucas Mello Schnorr (INF/UFRGS)
#+Date: schnorr@inf.ufrgs.br

#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS: [10pt, a4paper]
#+LATEX_HEADER: \input{org-babel.tex}

#+OPTIONS: toc:nil date:nil author:nil
#+STARTUP: overview indent
#+TAGS: Lucas(L) noexport(n) deprecated(d)
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport

Para esta lista de exercícios, vamos considerar a seguinte gramática
de declaração e acesso a elementos de arranjos.

\begin{center}
\begin{tabular}{lll}
 decl  &  $\rightarrow$  &  T \textbf{id} [ L ]  \\
 T     &  $\rightarrow$  &  \textbf{float} $\vert{}$ \textbf{int} $\vert{}$ \textbf{double} $\vert{}$ \textbf{char}     \\
 L     &  $\rightarrow$  &  L , D                \\
 L     &  $\rightarrow$  &  D                    \\
 D     &  $\rightarrow$  &  C..C                 \\
 C     &  $\rightarrow$  &  \textbf{num}         \\
atr & $\rightarrow$      & x = acesso \\
 acesso  &  $\rightarrow$  &  \textbf{id} [ L ]                   \\
 L       &  $\rightarrow$  &  L , E                               \\
 L       &  $\rightarrow$  &  E                                   \\
 E       &  $\rightarrow$  &  E + N                               \\
 E       &  $\rightarrow$  &  N                                   \\
 N       &  $\rightarrow$  &  \textbf{num} $\vert{}$ \textbf{id} $\vert{}$ acesso \\
\end{tabular}
\end{center}

Defina o esquema de tradução para cálculo da parte constante e da
parte variável do endereçamento de arranjos.

* Questão 01
\label{x} Calcular a árvore de derivação para cada um dos
  comandos seguintes:
  \begin{lista}
    \item $X = A[i]$
    \item $X = B[i, j+k]$
    \item $X = C[i, k, z]$
    \item $X = D[i, k, z, q]$
  \end{lista}

* Questão 02
\label{x1} Gere o código TAC correspondente para cada árvore do
  exercício~\ref{x} considerando as declarações seguintes:
  \begin{lstlisting}
    float A[10..-10] //um float ocupa 4 bytes, base=(fp+44)
    double B[7..-1][3..10] //um double ocupa 8 bytes, base=(fp+98)
    int C[0..3][3..-5][-10..3] //um int ocupa 4 bytes, base=(bss+30)
    char D[10..0][4..9][1..8][-4..7] //um char ocupa 1 byte, base=(bss+10)
  \end{lstlisting}

* Questão 03
\label{y} Complete o esquema de tradução desta lista com regras
  de geração de TAC para expressões aritméticas.

* Questão 04
\label{y2} Considerando o esquema de tradução resultante do
  exercício~\ref{y} e as declarações do exercício~\ref{x1}, construa a
  árvore de derivação para as seguintes expressões:
  \begin{lista}
    \item $x = A[s] + q$
    \item $x = A[i] + A[j]$
    \item $x = B[i*C[k+1],j+A[0]-B[i*i]] + A[j] * C[i,j,k]$
  \end{lista}

* Questão 05
Gere código TAC para cada uma das expressões do exercício~\ref{y2}.

* Questão 06
A expressão $x = a[b[i,j],c[k]]$ é aceita pela gramática do
  exercício~\ref{y}? Caso positivo, gere código TAC para ela. Caso
  contrário, altere a gramática para que isto seja possível e gere
  código TAC.

* Questão 07
\label{z} Um arranjo de inteiros $A[i,j]$ tem índice $i$ de 3 até 20 e
  índice $j$ de 4 até -10. Os inteiros ocupam 3 bytes. Suponha que o
  arranjo A seja armazenado a partir do endereço 5 e por
  linha. Encontre a localização de:
  \begin{lista}
    \item $A[3,-10]$
    \item $A[20,-10]$
    \item $A[11,-1]$
  \end{lista}

* Questão 08
Repita o exercício~\ref{z} considerando que A é armazenado por coluna.

* Questão 09
\label{w} Um arranjo do tipo ponto flutuante $A[i,j,j]$ possui
  índice $i$ variando de 1 até 4, índice $j$ variando de 0 até 4, e
  índice $k$ variando de 5 até 10. Os tipos reais ocupam 8 bytes
  cada. Suponha que o arranjo $A$ seja armazenado por linha a partir
  do byte 0. Encontre a localização de:
  \begin{lista}
    \item $A[3,4,5]$
    \item $A[1,2,7]$
    \item $A[4,3,9]$
    \item $A[1,0,5]$
    \item $A[4,4,10]$
  \end{lista}

* Questão 10
Repita o exercício~\ref{w} considerando armazenamento por coluna.
\end{listanumerada}
\end{document}
