all: ascendente.pdf descendente.pdf lalr1.pdf lr1.pdf sequencia.pdf ast.pdf erros-descendente.pdf ll1.pdf lr.pdf slr1.pdf bison.pdf glc.pdf lr0-grammars.pdf preditivos.pdf transformacoes.pdf construcao-ll1.pdf introducao.pdf lr0.pdf primeiro.pdf
include ../../Makefile.base
