#+STARTUP: overview indent
#+TITLE: Dúvidas da E4 do Projeto de Compilador
* E4
** DONE 2020-10-06 D0
*** Dúvida #1

Estou agora refazendo as ações semânticas feitas na etapa 3, de
forma a criar as entradas na tabela de símbolos, e me deparo com a
forma gramatical através da qual identifico variáveis globais:

#+BEGIN_EXAMPLE
var_global: tipo_estatico lista_identificadores_globais ';' ;

lista_identificadores_globais:  identificador_global
         | identificador_global ',' lista_identificadores_globais ;

identificador_global:    TK_IDENTIFICADOR 
         | TK_IDENTIFICADOR '[' TK_LIT_INT ']' ;
#+END_EXAMPLE

Dado que o reconhecimento da entrada é ascendente e da esquerda para a
direita, como posso definir o tipo do nodo dos identificadores globais
pertencentes à lista se apenas terei essa informação após toda a lista
ser processada na entrada?

Em outras palavras, a ordem na qual estas regras são processadas para
a entrada "int x,y;", por exemplo, é primeiro o reconhecimendo do tipo
"int", e depois os identificadores "x" e "y". Ao meu ver, isto requer
o uso de um atributo herdado da lista de identificadores, o que
levaria a um esquema L-atribuído, requerindo regras internas, como na
possível solução:

#+BEGIN_EXAMPLE
var_global: tipo_estatico {lista_identificadores_globais->tipo = tipo_estatico->tipo}
            lista_identificadores_globais {/*Insere na tabela de simbolos*/}';'
#+END_EXAMPLE

Esta interpretação é correta ou estou realizando algum equívoco? Caso
a interpretação esteja correta, isto é permitido no contexto do
trabalho?

*** Dúvida #2

Notei que nesta etapa não foi dado um arquivo "main.c" para que sejam
realizados os testes. Podemos então usar (e inclusive realizar a
entrega desta etapa com ele) o mesmo arquivo da etapa 3?

*** Dúvida #3

Enquanto atribuia os tipos correspondentes às palavras reservadas int,
float, etc. fiquei com dúvida quanto aos especificadores de tipo, isto
é, "const" e "static". Esta informação deve ser guardada em algum
lugar, ou devemos realizar algum tratamento especial nestes casos?

** DONE 2020-10-13 D1
*** Dúvidas #1

Boa noite professor, surgiram algumas dúvidas rápidas de se responder
sobre a etapa 4, se for mais conveniente nem precisa fazer um vídeo
sobre elas:

1) Os operadores unários "*"(Resolução de ponteiro) e "#"(Acesso a
   tabela hash) esperam qual tipo de identificador operando?

2) O operador ternário (exp ? exp : exp) requer que as expressões
   resultantes tenham o mesmo tipo (ou pelo menos tipos compatíveis)?

3) Funções podem ser recursivas? Em termos mais técnicos, devo inserir
   a declaração da função tanto na tabela de símbolos do seu escopo
   quanto na do escopo global?

4) Para realizar a transferência dos tipos entre variáveis estou
   usando um novo campo na union dos tokens, que contém o tipo das
   palavras reservadas "int", "float", etc. Isto é permitido?
** DONE 2020-10-14 D2
*** Dúvida #1

1) Podemos usar C++ ou o flex/bison suportam apenas C?

*** Dúvida #2

2) Segundo o enunciado, precisamos guardar literais na tabela de
   símbolos. Por que isso é necessário?
** TODO 2020-10-16 D3
*** Dúvida #1

Sobre a etapa 4, retornando na questão dos literais na tabela de
símbolos: o que não ficou muito claro pra mim é como lidar com
múltiplas ocorrências de um mesmo literal? Digamos que na passagem
pelo código fonte eu encontre o literal 2 e adicione ele na tabela
hash, e mais adiante eu encontre outro literal 2. Essa ocorrência é
adicionada na tabela hash (com alguma informação adicional, como
número da linha, para distinção) ou eu simplesmente ignoro e mantenho
sempre a primeira ocorrência?

*** Dúvida #2

Como dito no ultimo vídeo de dúvidas, devemos adicionar literais na
tabela. Como tratamos literais iguais? devemos adicionar multiplas
vezes? ou deixar apenas a que já temos? se for manter a anterior,
devemos alterar algo nos dados dela?

*** Dúvida #3

Como poderemos aceitar expressão de (string + string), adicionei na
gramática a possibilidade de char e string dentro das expressões, para
que esse caso seja permitido enquanto outras operações, e
transformações com esses tipos causem erro. Gostaria de saber para
casos como (string * string), por exemplo, que tipo de erro devemos
retornar? (dizer que está sendo feita alguma conversão da string e
utilizar o ~ERR_STRING_TO_X~?)

*** Dúvida #4

Na parte de conversão explicita, quando diz que "a conversão de um
float para int perde sua parte fracionária", é só uma explicação do
que será feito eventualmente no desenvolvimento do compilador?, não
devemos tentar alterar esse valor na tabela de nenhuma forma agora,
correto?

*** Dúvida #5

Para funções que tem retorno string, temos que definir o tamanho desta
com a maior string de retorno encontrada no corpo de uma função? Se
sim, se houver uma função recursiva com retorno string, isso pode
causar problemas por possivelmente não ter o valor "máximo" de retorno
até um determinado momento?

*** Dúvida #6

No caso de vetores de string, como tratamos o tamanho para os
elementos strings?


