# -*- coding: utf-8 -*-
# -*- mode: org -*-

#+TITLE: Dúvidas da E5 do Projeto de Compilador
#+Author: Lucas Mello Schnorr
#+Date: schnorr@inf.ufrgs.br
#+Language: pt-br

#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS: [11pt, a4paper]
#+LATEX_HEADER: \input{org-babel.tex}

#+OPTIONS: toc:nil title:nil
#+STARTUP: overview indent
#+TAGS: Lucas(L) noexport(n) deprecated(d)
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport

* E5 2020/2
** 2021-04-10 D0
*** Dúvida #1

Na main.c, temos "Não modifique o arquivo.", e queremos seguir esta
solicitação. Porém, há na main.c dois protótipos de funções: void
exporta (void *arvore); void libera (void *arvore); Onde devemos
implementar essas funções, já que não devemos alterar a main e estes
protótipos estão declarados na main? Além disso, se implementarmos em
outro lugar, precisaremos adicionar uma linha na main para adicionar
uma biblioteca, por exemplo, o que alteraria a main. Como procedemos?

---

R: Vamos supor que a implementação destas duas funções estão em outro
módulo, chamado "outro". Tu terás então um outro.c e outro.h. No
arquivo de cabeçalho (.h), tu terás então o protótipo das funções,
idênticos àqueles já colocados no arquivo main.c. No arquivo da
implementação (.c), tu terás as implementações das duas funções. Na
hora de compilar, tu vais compilar o arquivo main.c e depois o arquivo
outro.c. No hora de linkar, tu farás a ligação de main.o com outro.o,
e como em main.c a implementação das duas funções estará em aberto, o
linkador fará a linkagem com a implementação das duas funções do
módulo outro.o. E isso estará resolvido. Veja, portanto, que não há a
necessidade de alterar a main.c adicionando o include do outro.h tendo
em vista que o protótipo das duas funções é idêntico (entre o que já
temos em main.c e o que tu terás em outro.h). Claro, o ideal, seria
adicionar outro.h, mas se queres seguir a risca o comentário, essa
estratégia resolve. Dito tudo isso, o tal comentário erá mais para a
E3, agora na E5, podem se sentir a vontade para alterá-lo.
*** Dúvida #2

1 - Nas simplificações dessa etapa, devemos implementar a tradução
para vetores ou isso também não é necessário?

---

R: Não é necessário.

*** Dúvida #3

2 - Na parte que diz "Os programas a serem compilados devem conter
pelo menos a função main.  Ela deverá ser a primeira a ser executada"
as funções que não são main não precisam ser executadas (a menos que
tenham sido chamadas na main)?

---

R: Exato. As funções que não são main não devem ser executadas a menos
que tenham sido chamadas na main.

*** Dúvida #4

3 - Nas aulas sobre o ILOC, os registradores são inicializados com

 loadI 1024 => rfp
 loadI 1024 => rsp

Isso é necessário no projeto? E, caso não seja, podemos inicializar
esses registradores com outros valores ou isso atrapalhará na
avaliação?

---

R: Na avaliação, a primeira inicialização dos registradores rfp, rsp e
rbss é ignorada, pois ao avaliar o simulador é chamado com a seguinte
linha:

#+begin_src bash
timeout 3 ${ILOCSIM} \
        --stack $STACK \
        --data $DATA \
        -s \
        -x < /tmp/saida.iloc > /tmp/saida.sim
#+end_src

sendo que ILOCSIM é o path para o simulador, STACK e DATA são
endereços para a pilha e segmento de dados, respectivamente, gerados
de maneira aleatória, e ~/tmp/saida.iloc~ tem a saída ILOC gerada pelo
compilador do grupo. De acordo com o ~--help~ do simulador, os
parâmetros ~-s~ e ~-x~ significam, também respectivamente, que
estatísticas serão geradas e que um ambiente estrito para os
registradores rbss, rfp e rsp será adotado, ou seja, a primeira
definição do valores desses registradores no código ILOC da entrada
será ignorada. Ou seja, podem (e até devem) definir valores iniciais
para os testes de vocês, mas lembrem-se que esses valores iniciais
serão ignorados nos testes automáticos pois serão substituídos por
endereços aleatórios.

*** Dúvida #5

(continuação da dúvida #4 acima)

---

Fiquei em dúvida com relação a essa parte, pois pensei que tínhamos
que salvar o número de instruções geradas pelo programa para
inicializar o rbss com esse valor (para que o segmento de dados se
inicie logo após o código). Se o segmento de dados é iniciado
aleatoriamente, então isso não é necessário?

---

R: É necessário mesmo assim, eu avalio de maneira subjetiva esse aspecto.

*** Dúvida #6

(continuação da dúvida #4 acima)

---

E, também já que esses números são iniciados aleatoriamente, não há
risco do segmento de dados se iniciar no meio dos endereços da pilha,
ou no meio das instruções?

---

R: Pode deixar comigo que a geração de números aleatórios é controlada
para evitar esse tipo de problema. No simulador ILOC, o "espaço" de
memória do código e dos dados (pilha, dados, etc) é separado, ao
contrário da realidade onde existe apenas um único endereçamento.

** 2021-04-16 D1
*** Dúvida #1

Quando é dito que podemos considerar que existe apenas o tipo int,
podemos assumir que não haverá nenhum caso de teste que coloque outro
tipo (como, por exemplo: int[], float, bool ou string) e que espere
que a gente:

1 - Ignore que o tipo era diferente de int (mesmo sendo string, ou
int[]), e trate-os todos como int; ou

2 - Retorne uma exceção dizendo que o tipo recebido não é int.

Caso não hajam casos de teste com outros tipos, ou caso hajam, mas
estes não estejam vínculados a uma das 2 expectativas acima, então não
haverá problemas em:

1 - Ignorar totalmente os tipos, sem fazer qualquer verificação, e
tratar todos os identificadores como int (não-vetorial), mesmo sendo
eles argumentos de função, vetores, variáveis de outros tipos ou mesmo
retornos de função. Ou seja, fechar totalmente os olhos para os tipos
(exceto no que se refere às análises semânticas do E4 suponho, ou
mesmo elas deveríamos excluir?); ou

2 - Fazer extras, como por exemplo, lidar com diferentes tipos, ou
vetores.

Pergunto isso, pois caso hajam tais casos de testes com outros tipos,
e haja também uma expectativa vinculada a eles, teríamos que tomar
cuidado, e talvez não pudéssemos fazer alguma dessas opções listadas
por último.

Mas o que eu imagino pelo que está escrito, por exemplo aqui "Nada
precisa ser feito referente aos tipos diferentes de int", é que não
haverá qualquer caso de teste em que apareça algum tipo diferente de
int, e portanto a minha suposição de que poderia haver algum, e que
ele deveria ou retornar erro, ou deveria ser tratado como int, é
irrelevante. Contudo, pergunto para confirmar.

Ah, e isso se extende analogamente também para os comandos que foram
ignorados no E5. Se aparecer um "return X;", devemos lançar um erro,
devemos ignorá-lo, ou tanto faz? E se o return não deverá ser
implementado, assim como o break, continue, então não haverão jumps
relacionados a eles, caso apareçam? (essas perguntas são irrelevantes
caso eles não aparecerão em nenhum caso de teste)

---

R: Sobre a questão dos tipos de dados, reforço que haverá apenas o
tipo ~int~. Não haverá nenhum outro tipo de dado nos testes automáticos
da E5, conforme a especificação explicita. Minha sugestão é que não
sejam lançados erros (sejam eles quais forem) ao encontrar outros
tipos de dados, afinal a léxica/gramática/semântica se mantém
inalteradas. A opção por ignorá-los é portanto privilegiada.

R: Sobre a questão dos comandos que foram deixados de fora da E5, é
bem lembrada a importância do comando ~return~ especificamente, que se
integra bem às chamadas de função. Neste sentido, minha sugestão seria
implementar o comando ~return~, ainda que isso não esteja especificado
na E5. Se o grupo decidir não fazê-lo, afinal não está na
especificação da E5, minha sugestão é que não sejam lançados erros ao
encontrá-lo, apenas ignorá-lo. Invariavelmente o comando return será
implementado na E6.

R: Como o questionamento foi longo, não tenho certeza se respondi
tudo. Diga-me caso eu tenha deixado algo sem resposta.

*** Dúvida #2

Uma outra dúvida é a respeito dos identificadores static e const. Está
correto a minha interpretação?:

1 - Uma variável local do tipo static T não deverá ser interpretado
como uma variável local de tipo T comum, mas sim fará a variável ser
alocada no segmento de dados, em vez de no registro de ativação;

2 - Uma variável global do tipo static T deverá ser interpretada como
uma variável global do tipo T comum;

3 - Uma função com tipo de retorno static T deverá ser interpretada
como uma função com tipo de retorno T (que inclusive é irrelevante, já
que o return aparentemente não deverá ser implementado);

4 - Um parâmetro de função ou variável local de tipo const T deverá
ser interpretado como um parâmetro de função ou variável local
(respectivamente) de tipo T.

---

R: Embora ~static~ e ~const~ constem de fato na especificação sintática da
E2, não não exploramos esse assunto nas etapas subsequentes. A forma
de se implementar e verificar esses especificadores já poderiam ter
sido antecipados na E4 (análise semântica) e com certeza tem um
impacto evidente agora na E5 (geração de código intermediário). No
entanto, isso não faz parte da especificação da E5 primando pela
simplificação.

R: Mesmo assim, informo minha concordância caso o grupo deseje
implementar esses especificadores (deverão haver mudanças no que foi
feito na E4). Concordo com 1. Concordo com 2. Concordo com 3, mas veja
meu comentário sobre o comando ~return~ na resposta ao questionamento
anterior. Ainda sobre 3, veja que ~static~ de funções em geral é
implementado para restringir o escopo da função ao módulo. Não temos
módulos em nossa linguagem pois não almejamos aqui implementar linking
entre códigos objeto. Concordo com 4, a diferença é que sendo ~const~
(inspirando-se do C) tais variáveis não poderiam ser alteradas.

*** Dúvida #3

É possível utilizar Python3 para essa parte do trabalho, ou devemos
seguir com o C/C++? Acredito que essa área de síntese poderia ser
implementada sem problemas em outra linguagem, utilizando mecanismos
de subprocess call a partir da main.c.

---

R: Não pode usar Python3. Seguir com C/C++.

*** Dúvida #4

1) Estávamos pensando em uma forma de diferenciar registradores/labels
   dos ponteiros (rfp, rsp etc.). Inicialmente pensamos em usar uma
   estrutura de dados para isso (como um enum), mas, como os ponteiros
   são poucos em número, pensamos em diferenciar eles simplesmente
   definindo eles com valores negativos, já que registradores e labels
   não podem ser negativos e em ILOC eles são representados por uma
   string e não por um número. Isso faz sentido, ou temos que
   representar os ponteiros de outra maneira?

---

R: Penso que chamar rfp, rsp e demais temporários (todos começando por
"r") de "ponteiros" não é muito adequado, para evitar confusões com
ponteiros da linguagem de programação C. Muitos usam simplesmente
strings para referênciá-los. Outra opção talvez seja usar uma struct
que tenha um "tipo" (que poderia ser a enum que vocês mencionam) com
um número, sendo que tal número não fosse usado caso o "tipo" fosse de
algum registrador especial (como rbss, rfp ou rsp). Enfim, todas essa
escolhas são do grupo.

*** Dúvida #5

2) Para fazer o remendo, ao gerar o label do rótulo, podemos gerar ele
   como se fosse um label qualquer (sem ser remendo), ou precisamos
   marcar ele como sendo um label de rótulo, diferente dos outros
   labels? No momento implementamos da primeira forma, mas queria
   saber se isso não poderia causar problemas ao criar outros labels
   depois.

---

R: No caso de uma implementação da geração de código em uma passagem,
precisaremos de fato usar remendos. A "referência" a um "buraco" que
deverá ser remendado pode ser implementada de várias formas. Minha
sugestão é que, ao gerar um "buraco", vocês coloquem ali algo [uma
string] algo que certamente não vá funcionar caso o simulador seja
executado com a entrada, assim vocês podem facilmente detectar
eventuais erros. Quando a "referência" a implementação habitual é que
seja uma lista de ponteiros para campos que contém buracos a serem
remendados.

** 2021-04-17 D2
*** Dúvida #1

Como o código iLOC será o código da main, essencialmente, ao final do
processo de análise eu posso passar a main para o topo da AST?

---

R: Se houver no programa duas funções, primeiro a função foo e depois
a função main, idealmente, deveríamos ter na saída ILOC primeiro o
código ILOC de foo, depois o código ILOC de main. Sabendo que o
programa deve começar pela função main, antes do código de foo (e
depois da inicialização dos registradores principais - rsp, rfp,
rbss), podemos ter um jump para o início da função main. Creio que há
um exemplo disso na aula N12 A3 (slide 5/6). Bom, quanto a relação
disso com a AST, vocês podem fazer da forma que acharem mais oportuna,
mas veja que alterar a ordem das funções em código objeto (e aqui no
código intermediário) é algo que normalmente não se faz. Por que um
compilador mudaria a ordem do código das funções no código final?

*** Dúvida #2

Sobre as chamadas de funções:
1 - é necessário implementar chamadas recursivas?
2 - Caso seja necessário implementar chamadas recursivas, nos exemplos
da aula a função main é diferente das outras pois não inclui a
recuperação dos valores de rfp e rsp antigos, já que se supõe que é a
primeira a ser chamada. Se fôssemos implementar uma função main
recursiva precisaríamos criar uma rotina alternativa que incluisse
essas instruções?

---

R: 1. Sim; 2. A função main não precisa ter suporte à recursão, apenas
as demais funções.

*** Dúvida #3

Quando temos numa atribuição o código:

a = 5+5*3;

Precisamos fazer cada operação (soma e multiplicação, nesse caso) em
código iLOC, ou podemos apenas guardar o valor final (20), na memória?

---

R: Podemos deixar esse tipo de otimização para a E7. Ou seja, na E5,
podem gerar código mesmo que o compilador pudesse antecipar o
resultado final.

*** Dúvida #4

No código:

int a;
int f(){}
int b;
int main(){}

Como fazemos para irmos "direto" para a main, porém evitando a função
f e incrementando o ponteiro para os endereços das variáveis globais a
e b?

---

R: Cada função pode ter um label marcando seu início, e no preambulo o
grupo sistematicamente gera um salto incondicional para o label da
função main. Assim, não importa onde ela esteja, funcionará.

*** Dúvida #5

A primeira dúvida que tenho é se não faria sentido o compilador
decidir qual das sub-expressões, S1 e S2, avaliar primeiro por outra
regra diferente de sempre S1 primeiro (nas expressões: "S1 and S2" ou
"S1 or S2").

Por exemplo, não faria sentido eu avaliar qual código é maior, e
inferir que se o código de S1 é maior que o de S2, de modo que no
geral valeria mais a pena avaliar S2 primeiro, visto que se ambos
tiverem a mesma chance de ser verdadeiro/falso, em média, após
milhares de execução dessa abordagem, teremos um ganho de desempenho
frente à estratégia de executar S1 primeiro sempre?

Outra estratégia possível seria atribuir uma chance de ser verdadeiro
ou falso, para todo nó booleano, da seguinte forma: AND tem P1*P2
chance de ser verdadeiro, e 1-P1*P2 chance de ser falso; OR tem
1-P1*P2 chance de ser verdadeiro, e P1*P2 chance de ser falso, NOT tem
1-P1 chance de ser verdadeiro e P1 chance de ser falso, "false" tem 0
de chance de verdadeiro [...] Assim por diante, e comparadores
relacionais ou identificadores booleanos tem chance de 50%/50%. E
considerar essas chances para determinar por exemplo, que o OR deve
avaliar primeiro a sub-expressão de maior chance de ser verdadeira (e
o AND, o contrário).

Outra estratégia seria fazer um híbrido das duas acima.

Bastaria deixar claro que o compilador faz isso, para que o
programador não espere um curto-circuito sequencial.

Ou existiria algum problema em fazer isso?

---

R: Em geral as linguagens de programação assumem que as coisas são
avaliadas da esquerda para a direita. Em C, por exemplo, temos a
implementação de curto-circuito e todos os programadores da linguagem
C que conhecem bem a linguagem sabem disso, tirando usufruto. Claro, a
descrição da linguagem poderia ser mais elaborada, considerando tudo
que propuseste, mas creio que isso em geral existe apenas através de
operadores especiais, diferentes daqueles padrões da linguagem. Na
disciplina de MLP, por exemplo, vemos que a linguagem Ada possui
operador do e lógico com e sem curto-circuito. Ainda que bem mais
simples do que as ideias acima, seria um caminho a ser tomado: usar
operadores diferentes para ativar tal tipo de funcionalidade. Mas
minha visão é que muitas dessas coisas seriam mais a cargo do ambiente
de execução, e menos do compilador. Veja que avaliar o "tamanho do
código" passa por definir "tamanho". Um código pode ser longo e
rápido, um código curto pode ser lento.

*** Dúvida #6

Outra dúvida que tenho é a respeito de implementar a avaliação de
expressão lógicas por controle de fluxo por sistema S-Atribuído. Não
daria para fazer sem remendos?

O que eu estava pensando era em sempre armazenar o resultado de uma
expressão lógica em um registrador (assim como na avaliação numérica).

Assim, se a expressão lógica E, aparecer dentro de um "if (E) {C1}
{C2}", quando eu avaliasse o nó do if, eu simplesmente concatenaria o
código de E, com um código intermediário, seguido dos códigos de C1 e
C2, de tal modo que o código intermediário conteria um jump
condicional para C1 ou C2, usando como base o conteúdo do registrador
que armazenou o resultado de E.

Posteriormente, em uma etapa de otimização, seria fácil percorrer o
código e remover esses registradores que só servem para determinar um
branch.

Isso foi referente ao uso da expressão E no nó acima dela. Já quanto
ao uso das sub-expressões de E, em E, por exemplo E1 e E2, em "E1 and
E2", também creio que seria trivial fazê-los de modo a ter
curto-circuito.

Uma das formas triviais que pensei seria converter "E1 and E2" para
"if (E1) {r = E2} else {r = false}", e gerar o código referente (que
teria curto-circuito por definição). (Essa é a minha versão favorita,
mas outra opção seria manualmente fazer esse código, com dois branchs,
um a partir de E1, que pode pular direto para um "loadI 0 => r", que
pula para um NOP final, ou então para o segundo branch, que seria a
partir de E2 e pode pular para "loadI 1 => r" ou "loadI 0 => r", ambos
que pulam para o NOP final.)

Resumindo:
- Nenhum nó meu que é do tipo booleano (OR, AND, NOT, LE, GT, EQ,
  ...), vai ter um jump para algo externo e desconhecido, todos eles
  vão simplesmente armazenar um valor booleano em um registrador do
  próprio nodo e terminar a execução.
- Todo nó meu com curto-circuito (IF, AND, OR) utilizará o valor do(s)
  registrador(es) do(s) nó(s) de sua(s) sub-expressão(ões) booleana(s)
  para fazer o curto-circuito.
- Uma etapa de otimização colapsará cada registrador que só é
  utilizado para receber constantes 0 e 1, e depois fazer um branch
  condicional, para então fazer branchs diretos.

Só isso, sem sistema L-Atribuído, sem remendos (considerando que essa
otimização é opcional, pois mesmo sem ela, ainda há curto-circuito).

Há algum erro?

---

R: Acredito que fazer um esquema S-atribuído que implemente curto
circuito sem remendos seja difícil quando a escolha do salto, o
destino, aparece apenas depois da decisão lógica. Veja que as
expressões lógicas normalmente aparecem antes do alvo para os quais
elas decidem para onde desviar. É o caso do if, do for, do while,
etc. No exemplo que deste, veja que C1 e C2 só aparecem depois que E
apareceu. Claro, tu podes não fazer nada nas produções de E, fazendo
tudo na regra do if, mas isso implica em algo não S-atribuído, por
definição. Então, em suma, a resposta, acredito que não dê para fazer.

*** Dúvida #7

Pensando em como eu iria implementar um registro de ativação de uma
função com diversos blocos aninhados não-nomeados de comandos, com
próprias variáveis locais, no projeto, cheguei em uma solução que
considero um pouco mais eficiente de a vista em aula.

Por exemplo, considere a seguinte função:

int f()
{
   int a = 1;
   {
       int b = 2;
   }
   int c = 3;
}

Para esta função, o método visto em aula alocaria um registro de
ativação com 12 bytes para variáveis locais (considerando que cada
variável do tipo int tem tamanho 4 bytes), contudo, eu vejo uma forma
de utilizar só 8 bytes, que seria a seguinte:

Sempre que eu desempilho um bloco de comandos aninhado, eu decremento
o tamanho de bytes que suas variáveis locais ocupavam, e permito as
próximas variáveis locais utilizarem o mesmo espaço que aquelas antes
ocupavam, visto que isso nunca gerará conflito, já que aquelas agora
não serão mais utilizadas, nunca mais.

Também armazeno qual foi o tamanho máximo de bytes necessários em
qualquer ponto do código da função, e utilizo isto como o tamanho da
parte de variáveis locais do registro de ativação da função.

Existe algum erro de análise / não devo fazer deste modo por conta de
algum sistema de correção automático? 

---

R: Pode implementar assim, não vejo problemas na análise subjetiva. Na
análise objetiva (correção dita "automática") considera-se o estado
final da memória, ou seja, os endereços para os quais foram atribuídos
valores. Neste sentido, pode ter um teste, veja bem, pode, que
esperaria encontrar o valor 2 em um endereço de memória. Implementando
a otimização descrita, o valor 2 não seria encontrado pois seria
sobrescrito por 3 tendo em vista que a variável c iria ocupar o mesmo
endereço de b. Neste caso, o teste falharia. Dito isso, como escrevi,
pode, acredito que não tenha um caso desses nos testes que já preparei
de antemão mas que depois modifico, dentro do possível pedagógico, em
função do desempenho dos grupos.

* E5 2020/1
** DONE 2020-10-23 D0
*** Dúvida #1
Foi mencionado em um dos vídeos de dúvidas da etapa 4 que os literais
deveriam ser guardados na tabela de símbolos, pois acabariam na área
de dados do programa. Naquele vídeo, foi dito que esta inserção pode
ser feita na tabela de símbolos do escopo onde ele é encontrado, e foi
assim que implementei a etapa 4. Agora com o conhecimento sobre a
geração do código, refleti sobre este posicionamento, e acredito que
para que o literal acabe no segmento de dados ele deve ser inserido na
tabela de símbolos global, contabilizando seu tamanho também na
geração de endereços da mesma.

#+BEGIN_EXAMPLE
int y;

int main()
{
    int x <= 5;
}
#+END_EXAMPLE

Na forma que implementei na etapa 4 tenho as tabelas:

GLOBAL  (Endereço corrente ao final do reconhecimento = 8. )
| Nome | Tamanho | Endereco |
|------+---------+----------|
| y    |       4 |        0 |
| main |       4 |        4 |

MAIN (Endereço corrente ao final do reconhecimento = 8. )
| Nome | Tamanho | Endereco |
|------+---------+----------|
| x    |       4 |        0 |
| "5"  |       4 |        4 |

Porém após a reflexão, imagino que o correto seria:

GLOBAL (Endereço corrente ao final do reconhecimento = 12)
| Nome | Tamanho | Endereco |
|------+---------+----------|
| y    |       4 |        0 |
| main |       4 |        4 |
| "5"  |       4 |        8 |

MAIN (Endereço corrente ao final do reconhecimento = 4)
| Nome | Tamanho | Endereco |
|------+---------+----------|
| x    |       4 |        0 |

Para que o literal "5" acabe no data segment.

Qual das duas está correta? Em outras palavras, devo inserir o literal
no frame da função onde aparece ou no data segment do programa como um
todo?
** DONE 2020-11-02 D1
*** Dúvida #1

Quanto a etapa5, você poderia montar um exemplo um pouco mais concreto
de uma saida iloc para um arquivo simples de entrada?

e como podemos conferir se um programa nosso está executando
corretamente no simulador com um exemplo de como será a avaliação do
trabalho?

*** Dúvida #2

Olá professor, na etapa 4 implementamos os blocos de instruções como
sendo uma nova tabela. Na etapa 5, temos que definir os endereços das
variáveis.  Na aula N10 A5, você explica que para escopos anônimos, o
deslocamento do escopo anterior deve ser atualizado ao se fechar o
escopo anônimo. Porém, levando em conta nossa implementação, isso
continua válido? Pois, ao fechar-se o escopo anônimo, a sua tabela
deixaria de existir. Ao atualizar o deslocamento, estaria se
considerando que as variáveis do bloco anônimo (já fechado) continuam
existindo.

*** Dúvida #3

Outra dúvida seria sobre o endereçamento. Devemos começar no endereço
mais alto (seria 2^64?) como no C, ou no 0?

*** Dúvida #4

Quanto a parte de criação pro programa iloc, quando houver uma chamada
de uma função, `f()` por exemplo, eu preciso criar novos dados na
pilha pra cada chamada de função, correto? então, se for uma função
recursiva, deveriamos criar isso varias vezes. Como que criamos a
tabela durante a execução, já que não teriamos como saber quantas
vezes a função seria chamada, ou não precisamos tratar isso e
"reutilizar" as variaveis definidas?

*** Dúvida #5

Estou com umas duvidas quanto a utilização dos registradores
reservados (rbss, rfp), de acordo com o que diz em aula, esses valores
são definidos por padrão, exemplo do rbss que não se altera durante a
execução. Em nosso programa, não precisamos nós mesmos manter controle
deles durante a execução? Peço isso especialmente quanto a ideia do
empilhamento em uma chamada de função, pois não entendi muito bem como
manter o controle deles em casos assim.

*** Dúvida #6

Se a entrada começar com a seguinte declaração de variáveis globais:

int a, b;

é necessário que o deslocamento da variável "a" seja 0 e o da variável
"b" 4, ou é aceitável que "b" apresente o deslocamento 0 (pois estamos
adicionando as variáveis na tabela de símbolos na ordem inversa)?
** DONE 2020-11-04 D2
*** Dúvida #1

Surgiu uma dúvida enquanto implementava a geração de código para a
declaração de funções, em especial a função 'main'

No início do programa, implementei aquele trecho de código padrão que
carrega os valores de rfp, rsp e rbss iniciais, e então um 'jump' para
o label da função 'main'. A função main, ao encerrar, deve retornar a
este trecho de código para que se possa encerrar o programa, ou ela
mesmo deve encerrar? Isto é, devo tratar este trecho inicial como
fazendo uma 'chamada de função' à main, passando nenhum argumento, e
executando a instrução HALT no retorno, ou devo inserir
aritficialmente a instrução HALT no final do código da função main?
Isto leva a outra pergunta: a função main deve ter um comando 'return'
no seu fim? ou apenas o comando HALT?

*** Dúvida #2

Surgiu uma dúvida sobre a linguagem ILOC: ao usar uma constante em uma
determinada instrução, ela pode ser um número negativo?  Por exemplo,
"loadI -1 => r0".

*** Dúvida #3

Novamente tratando dos literais, quando eles são delcarados e
colocados na tabela de símbolos globais, eles recebem um endereço no
qual seu valor estará presente, como explicado no primeiro vídeo de
dúvidas. Porém, não entendi como estes literais receberão o valor que
de fato representam para que o código possa acessar seu valor;
Exemplo.:

#+BEGIN_EXAMPLE
int main(){
    int x;
    x = 2;
}
#+END_EXAMPLE

Aqui, o literal 2 é declarado na tabela de símbolos global, com
endereço, por exemplo, 4. A geração de código segue como normal, e na
atribuição este endereço é acessado corretamente pelo programa. O
problema é: Este endereço possui o valor 0, já que não foi
inicializado. Em que ponto do código (Na criação do nodo do literal,
na declaração na tabela de símbolos, na própria atribuição, etc) devo
inserir uma instrução ILOC que carrega o valor 2 naquele endereço?
Quanto ao código ILOC gerado no final da execução, onde este 'store'
de literais deve aparecer? Na primeira ocorrência do acesso ao vetor?
ou então antes mesmo de realizar o 'jump' para a função main?
** DONE 2020-11-09 D3 (pós-deadline)
*** Dúvida #1

No último vídeo de duvidas (especificamente na terceira dúvida) é
comentado sobre os literais no segmento de dados. Você diz como
resposta que os literais deveriam ser inseridos na parte
correspondente do segmento de dados com código explicito de "store"
dos literais (pelo menos foi o que entendi). Isso é realmente
necessário nessa etapa? porque eu (ainda) não mexi na tabela de
símbolos para colocar todos os literais na tabela global, e você
comentou anteriormente que por estarmos tratando apenas inteiros, eles
caberiam direto em uma instrução iloc.

Por exemplo, deu-se a entender que para o exemplo do vídeo anterior:
int main() {
    int x;
    x = 2;
}

o literal 2 deveria ser armazenado na parte de segmento de
dados. Porém, poderiamos fazer diretamente o load de 2 para um
registrador, sem precisar carregar o dado do endereço do literal 2.

*** Dúvida #2

Estava testando meu programa com a seguinte função Fibonacci

int fib1(int a) {
    if (a == 0) {
        return 0;
    };
    if (a == 1) {
        return 1;
    };
    return fib(a-1)+fib(a-2);
}

mas o resultado dela está dando errado devido aos registradores sendo
usados na recursão das funções. Acontece quando, por exemplo, um
registrador r5 guardando o valor de fib(a-1), tem seu valor alterado
na própria recursão quando o valor de a é necessario para chamar a
recursão.

O problema some caso faça o seguinte:

int fib2(int a) {
    if (a == 0) {
        return 0;
    };
    if (a == 1) {
        return 1;
    };
    int aux1, aux2;
    aux1 = fib(a-1);
    aux2 = fib(a-2);
    return aux1+aux2;
}

assim os valores antes são devidamente guardados nas variaveis dentro
do RA da funcao fib.

Queria saber se nos programas de correção terá casos como em fib1, em
que tenhamos que ter maior cuidado com as chamadas de função
recursivamente, ou se será como em fib2, com variaveis para auxiliar o
processo.
