#+STARTUP: overview indent
#+TITLE: Dúvidas da E6 do Projeto de Compilador
* E6
** DONE 2020-11-16 D0
*** Dúvida #1

Somente um esclarecimento em relação à spec da E6:

O objetivo da etapa é a transcrição ILOC p/ Assembly, sem precisar
lidar com limites práticos de registradores ou implementar a alocação
por k-coloração neste momento?

Isso viria na etapa 7, junto com outras otimizações da semana 13?

*** Dúvida #2

1. Na etapa anterior do projeto tinhamos "infinitos" registradores
   para usarmos. Agora trabalhando com assembly já não temos mais essa
   facilidade. Devemos tentar diminuir a quantidade de registradores
   usados na nossa etapa anterior ou temos alguma forma mais simples
   de escolher registradores sem que haja "derramamento" deles?
** TODO 2020-11-18 D1
*** Dúvida #1

1) Nos códigos assembly que gerei fazendo alguns testes não
   identifiquei a inicialização dos registradores especiais nem um
   tipo de jump para o código da main, como fizemos com o ILOC. Esses
   passos ainda são necessários?

*** Dúvida #2

2) Com ILOC implementamos a pilha crescendo "para cima", mas no
   assembly a pilha cresce "para baixo". Isso é obrigatório?
   Precisamos "inverter" a pilha nessa etapa?

*** Dúvida #3

3) Precisamos gerar o assembly a partir do código intermediário que
   fizemos ou seria possível gerarmos ao mesmo tempo que reconhecemos
   a entrada, na primeira passada? Pergunto isso pois, vendo algumas
   instruções no assembly me parece ser mais simples gerar direto.

*** Dúvida #4

1. No enunciado da E6 dizes que podemos fazer a chamada de função
   utilizando os comandos "call" e "ret" (para o retorno). Gostaria de
   saber se tem como fazer a chamada sem utilizar esses comandos e
   seguir os passos já construídos na etapa anterior. No enunciado não
   mencionas nada de um registrador para o PC.

*** Dúvida #5

Eu e outros colegas estavamos procurando pela coleção de instruções e
nos deparamos em diferentes definições de como o assembly
funciona. Alguns lugares dizem que em uma instrução, por exemplo, "add
eax, edx", será feita a soma e depois o valor inserido em eax
(tutorial que deu o link no enunciado da E6), mas outros lugares
mostram exemplos em que o resultado da soma do exemplo será armazenado
em edx (ASM gerado pelo gcc). Só gostaria que o senhor confirmasse
isso corretamente conosco.
