# -*- coding: utf-8 -*-
# -*- mode: org -*-
#+startup: beamer overview indent
#+LANGUAGE: pt-br
#+TAGS: noexport(n)
#+EXPORT_EXCLUDE_TAGS: noexport
#+EXPORT_SELECT_TAGS: export

#+Title: Compiladores
#+Author: Prof. Lucas M. Schnorr (UFRGS)
#+Date: \copyleft

#+LaTeX_CLASS: beamer
#+LaTeX_CLASS_OPTIONS: [xcolor=dvipsnames, aspectratio=169, presentation]
#+OPTIONS: title:nil H:1 num:t toc:nil \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+LATEX_HEADER: \input{../org-babel.tex}

#+latex: \newcommand{\mytitle}{Recursivo com Retrocesso (Força Bruta)}
#+latex: \mytitleslide

* Introdução

#+BEGIN_CENTER
Como reconhecer se a sentença pertence a gramática?
#+END_CENTER

#+Latex: \vfill\pause

Características gerais
- Ler da esquerda para a direita
- Derivação mais à esquerda de não-terminais

#+Latex: \vfill

Estratégias descendentes
- Recursivo com retrocesso (força bruta)
- Preditivo: LL(1), com noção de /lookahead/
  - Recursivo
  - Tabular (autômato com pilha)

* Recursivo com retrocesso (força bruta)

+ Considerando a gramática \\
  $S \rightarrow A\ B$ \\
  $A \rightarrow c\ |\ {\epsilon}$ \\
  $B \rightarrow cbB\ |\ ca$
+ Ela gera $S \Rightarrow^* cbca$ ? @@latex:\pause@@ Vejamos...
  #+BEGIN_EXPORT latex
  {\medskip\scriptsize
  \begin{tabularx}{\textwidth}{llX}
  S     & cbca &  $S \rightarrow AB$ \\
  AB    & cbca &  $A \rightarrow c$ \\
  cB    & cbca &  consome c \\
  B     &  bca &  $B \rightarrow cbB$ \\
  cbB   &  bca &  retrocesso \\
  B     &  bca &  $B \rightarrow ca$ \\
  ca    &  bca &  retrocesso \\
  AB    & cbca &  $A \rightarrow \epsilon$ \\
  B     & cbca &  $B \rightarrow cbB$ \\
  cbB   & cbca &  consome c e b \\
  B     &   ca &  $B \rightarrow cbB$ \\
  cbB   &   ca &  consome c \\
  bB    &    a &  retrocesso \\
  B     &   ca &  $B \rightarrow ca$ \\
  ca    &   ca &  consome c e a \\
  $\empty$   & $\empty$  &  entrada reconhecida
  \end{tabularx}
  }
  #+END_EXPORT

* Reflexão

Fácil de implementar
+ Cada não-terminal é implementado como uma função
+ Mas é ineficiente, custo aumenta com o tamanho da entrada

#+latex: \vfill\pause

Qual o requisito fundamental?
+ Gramática não pode ser recursiva à esquerda \linebreak
  $A \rightarrow Aa \vert b$ \\
  + Considerando a entrada *ba* que pertence a essa gramática

#+latex: \vfill\pause

A gramática precisa ser fatorada a esquerda?
+ Ambiguidade na escolha da derivação influencia?
